name: Github Actions with Maven
on:
  push:
     branches: [ main ]
jobs:

  build:
   runs-on: ubuntu-latest
   steps:
    - name: set up JDK 1.8
      uses: actions/setup@v1
       with:
        java-version:1.8
        
   - name: Have Github Actions Build Maven Project
     run: mvn -B package --file pom.xml
     
   - name: List The Current Directory
     run:  ls -a
     
   - name: What is in the target folder?
     run: |
        cd target
        ls -a
    
  
      
               
                 
   
